### ISSUE TITLE
master.cpp's functions are using inconsistent linkage

### ISSUE THREAD

**Issue by daantimmer** [tdjastrzebski/All-Purpose-Power-Micro-Controller#1]
Master.h uses c-linkage and master.cpp use C++-linkage.

**Comment by tdjastrzebski** [comment]
Please elaborate.

**Comment by daantimmer** [comment]
The header (master.h) uses `extern "C"` to make the header link compatible with C and C++.
The source file (master.cpp) compiled by a C++ compiler will use C++ linkage (essentially impies `extern "C++"` see: https://en.cppreference.com/w/cpp/language/language_linkage for more information.

Your master.cpp file's functions however are not declared `extern "C"` so there now exists two type of functions, one _with_ an implementation and C++ linkage and one _without_ an implementation and C linkage.

Some compilers will allow this to work, but it is non-standard. As an example: https://godbolt.org/z/sYG4cq6dM

Take a look on the right side, and see how the names for MyFunc2 and MyFunc3 have some 'garbage' infront and behind the name? That is the C++ linkage stuff.

To solve this you'll have to mark all the functions in the master.cpp file as `extern "C"` as well.

**Comment by tdjastrzebski** [comment]
Thank you, I will try to fix it. I admit, I am not C/C++ expert.

**Comment by tdjastrzebski** [comment]
Please check if now it is ok.

**Comment by daantimmer** [comment]
See #2 for the correct changes :-)

Another option would be to change Master.cpp to just Master.c and treat it like a c-file instead of a c++ file. Only requires a c++ header to be substituted with a c header. (cstdlib -> stdlib.h)
